# For more information about the configurations used
# in this file, please see the Travis CI documentation.
#
# https://docs.travis-ci.com

script: if .travis/build-condition.sh $TRAVIS_COMMIT_RANGE $PROJECT; then echo "$PROJECT is being built"; else echo "$PROJECT is NOT being built"; fi

language: node_js
node_js:
  - 'lts/*'

matrix:
  include:
    - os: linux
      dist: trusty
    - env: PROJECT=frontend/
    - env: PROJECT=backend/

notifications:
  email:
    on_failure: always
    on_success: never

sudo: false
